name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.0]

    steps:
    # Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r requirements.txt
        pip install pytest 
        pip install coverage

    # Run tests
    - name: Run tests with pytest
      run: |
        pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=src/your_library --cov-report=xml
      env:
        CI: true

    # Upload test results
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: junit/test-results.xml

    # Upload code coverage report
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
